spring:
  datasource:
    url: jdbc:mariadb://localhost/memberize?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: memberize
    password: memberizepw
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 5010