spring:
  datasource:
    url: jdbc:mariadb://localhost/memberize?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: memberize
    password: memberizepw
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
server:
  port: 5010